### PR TITLE
Update REST API URL from /partner to /project

### PR DESCRIPTION
**Pull request by aiham**
/partner is deprecated and will no longer be supported from July 2017

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/opentok/OpenTok-PHP-SDK/pull/180" target="_blank">ReviewNinja

**Comment by aiham** [comment]
This is failing because of incompatible dependencies.

phing/phing(dev-master) requires phpunit/phpunit >=3.7 which requires sebastian/version ^2.0
phpunit(~4.1) requires sebastian/version ~1.0

So sebastian/version is conflicting.

I'll try to update the version of phpunit that we're using.

**Comment by tushar-1health** [comment]
Any ETA on when will this be released to packagist?

**Comment by aiham** [comment]
@tushar-1health This has been released as v2.5.0

**Pull request merged**
