### PR TITLE
PHP8 support

### PR DESCRIPTION
**Pull request by Jaspur**
PHP7.4 will be also EOL soon. PHP8 has the future. This PR brings support for PHP8.

### CODE REVIEW

**Comment by Jaspur** [comment]
@dragonmantank Tested and works. It was because of the deprecated `libxml_disable_entity_loader`

**Comment by dragonmantank** [comment]
Thanks for this! There's actually some dev dependencies that break with PHP 8, so will see if we can resolve those. Can you allow upstream access to your PR?

**Comment by Jaspur** [comment]
Where can I configure that?

**Comment by dragonmantank** [comment]
These should be the correct instructions:

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by Jaspur** [comment]
“Allow edits by maintainers” is checked ☑️

**Review by dragonmantank — APPROVED** [review]
LGTM, will get the version bumped and pushed out by the end of the day!

**Comment by dragonmantank** [comment]
This is released as 4.8.0 via Packagist!

**Pull request merged**
