### PR TITLE
Adds sessionId to listArchives api call

### PR DESCRIPTION
**Pull request by magroski**
Adds `listArchives` missing `sessionId` parameter as described on the the docs:
https://tokbox.com/developer/rest/#listing_archives

### CODE REVIEW

**Comment by magroski** [comment]
@msach22 done

**Comment by msach22** [comment]
@magroski We plan on releasing this week, please let me know if you have some time to fix the mock test. I'm also happy to commit to your branch if you're okay with that.

**Comment by magroski** [comment]
@msach22 I'm ok with you committing to my branch. I think the idea of the test is correct, but I'm unsure about the payload because I don't know if the api key that I'm using on the test will be able to decode the sessionId.

**Comment by msach22** [comment]
@magroski I'm closing this PR, but I've cherry picked your commits in the new PR 😄

**Pull request closed without merging**
