### PR TITLE
Upgrade to PHP7.2

### PR DESCRIPTION
**Pull request by rumeau**
This PR should point to a new version as ends compatibility with PHP5.6, 7.0 and 7.1.

Upgrades to:
 - PHP >= 7.2.5
 - Guzzle ^7.0.1
 - PhpUnit ^8.0

Update tests to version changes.

### CODE REVIEW

**Comment by dragonmantank** [comment]
Hello! This is actually something we've already started to work toward in the [`dev` branch](https://github.com/opentok/OpenTok-PHP-SDK/tree/dev), so if you could rebase and retarget against that it would be great.

**Comment by rumeau** [comment]
> Hello! This is actually something we've already started to work toward in the [`dev` branch](https://github.com/opentok/OpenTok-PHP-SDK/tree/dev), so if you could rebase and retarget against that it would be great.

The problem with this PR is that is using Guzzle 7.X and Dev branch is on 6.x. This makes it impossible to work under php7.2.

Requirements on SDK should be upgraded to PHP7.2 or greater in order to work. Otherwise PR should need to point to Guzzle 6.x but current SDK already works on that version and from PHP >=5.5

I will gladly update this PR if ypu are willing to upgrade guzzle version on dev too.

**Comment by Jaspur** [comment]
@dragonmantank when will this be done?

**Comment by dragonmantank** [comment]
In the near future.

Unfortunately, the issue is more with the dependency on Guzzle more than anything, and breaking that out than straight PHP 7.2 compatibility. We have a large number of existing customers on Guzzle 6 who may not be able to upgrade to Guzzle 7 (we had a similar issue with Guzzle 5 -> 6, and then 6 -> 7 on the [Vonage PHP SDK](https://github.com/vonage/vonage-php-sdk-core)). Conflicting HTTP clients are, unfortunately, a very common problem with PHP packages since we have to consider various frameworks developers use, not just what version of PHP they are on. You can happily run Laravel 6 on PHP 7.4, but then you'll most likely be running Guzzle 6 as well. We don't want to lock those users out.

We could just strip Guzzle out completely and recommend it via Composer, but that provides an additional hurdle for developers, especially newer developers.

Right now the focus is on removing the direct dependency on Guzzle to instead support PSR-18, and then providing a wrapper library so developers can chose either the "kitchen sink" install with Guzzle, or one without. That with migration is a much more delicate process.

**Comment by Jaspur** [comment]
Ok, so this year it’ll be released? We need indeed guzzle 7!

**Comment by dragonmantank** [comment]
> Ok, so this year it’ll be released? We need indeed guzzle 7!

Correct!

**Review by alexanderkraemer — APPROVED** [review]

**Comment by dragonmantank** [comment]
Closing, this work was done as part of getting Guzzle 7 updated. Thank you for the PR though!

**Pull request closed without merging**
